### ISSUE TITLE
Location Null in some cases

### ISSUE THREAD

**Issue by shivamdhammi** [Asgardian8740/NewsBuddy#1]
In a few cases, it returns in Null location.
One of the cases is when I start your app for the first time.
It was working smoothly after the first run.

**Comment by Asgardian8740** [comment]
> In a few cases, it returns in Null location.
> One of the cases is when I start your app for the first time.
> It was working smoothly after the first run.

Fixed

**Comment by shivamdhammi** [comment]
Chl jootha😂
